<?php

namespace app\widgets\DaoUserWidget;


use yii\base\Widget;

class DaoUserWidget extends Widget
{
    public $user;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->user)) {
            throw new \Exception('Не указан пользователь');
        }
    }

    public function run()
    {
        return $this->render('index', ['users' => $this->user]);
    }
}